### ISSUE TITLE
feat/ improve NarrativeText detection for docx

### ISSUE THREAD

**Issue by shreyanid** [Unstructured-IO/unstructured#1320]
Currently, the `STYLE_TO_ELEMENT_MAPPING` in [partition/docx](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/docx.py) detects most elements as Text when plenty could be classified as NarrativeText.

There appears to be a check for NarrativeText in the [`_text_to_element`](https://github.com/Unstructured-IO/unstructured/blob/09cc4bfa5ffbb4b17e03ebae0ad7fa554798da13/unstructured/partition/docx.py#L269C5-L269C21) function, but this check only occurs in the case of lists or when no element class is detected, which is not the case for documents identifiable with styled elements.

This enhancement is to further categorize Text elements classified via the `STYLE_TO_ELEMENT_MAPPING` into the more specific NarrativeText category, based on rules that would qualify it for that element type.

**Comment by cragwolfe** [comment]
CC @scanny

**Comment by scanny** [comment]
@shreyanid After a close look I'm not seeing any "smoking gun" as to how potential `NarrativeText` would be slipping through en-masse. I wonder if you can provide an example document or two where something you thought should be NarrativeText was classified otherwise, that would help a lot to clarify what you're seeing and put our finger on a cause.

The current element-type assignment logic for a paragraph in a .docx file is this sequence:

* **Paragraph is a list-item.** If the paragraph can be identified as a list-item, it gets type `ListItem`.

* **Paragraph has a differentiated paragraph-style.** If the paragraph has been assigned a _differentiated style_ from the Word document stylesheet/gallery, the type mapped in `STYLE_TO_ELEMENT_MAPPING` is used. A differentiated style is any style other than the default "Normal". The resulting type is currently one of `Title`, `ListItem`, or `Text` depending on the style.

All other paragraphs go to `_text_to_element()`, which handles these cases:

* **Paragraph is an entity.** If the paragraph can be identified as a U.S. city+state+zip it is assigned `Address`. If it can be identified as an email address it is assigned `EmailAddress`.

* **Paragraph is considered for `NarrativeText`.** The paragraph is assigned `NarrativeText` unless disqualified by `unstructured.partition.is_possible_narrative_text()`. There are a variety of resons, but they all look reasonable to me, like all numeric, text is empty string, most of the text is in all-caps, etc.

* **Paragraph is considered for `Title`.** The paragraph is assigned `Title` unless disqualified by `unstructured.partition.is_possible_title()`. That would be reasons like all-numeric, empty, multiple sentences, etc.

* **Paragraph is assigned `Text`.** If the paragraph doesn't meet any of the prior criteria it gets `Text`.

**Comment by scanny** [comment]
@shreyanid closing this as not actionable. Feel free to reopen if we identify specific cases.
