### ISSUE TITLE
TypedDict not available in python < 3.8

### ISSUE THREAD

**Issue by Mandeep258** [Unstructured-IO/unstructured#1330]
**Describe the bug**

**To Reproduce**
try parsing documents in python 3.7 versions as setup.py file's python requirement is >=3.7 and pip install didn't throw any errors.

**Expected behavior**

Import smoothly and parse documents.

**Screenshots**

from unstructured.documents.elements import (
  File "/home/airflow/.local/lib/python3.7/site-packages/unstructured/documents/elements.py", line 14, in <module>
    from typing import Any, Callable, Dict, List, Optional, Tuple, TypedDict, Union, cast
ImportError: cannot import name 'TypedDict' from 'typing' (/usr/local/lib/python3.7/typing.py)

**Environment Info**
Please run `python scripts/collect_env.py` and paste the output here. 
This will help us understand more about the environment in which the bug occurred.

**Additional context**

Either update setup.py which will not install the library on the first hand, which is not that helpful as one have to install whole new python or add a condition which would import same from typing_extensions

**Comment by scanny** [comment]
We'll need to use `typing_extensions` (and add it to package dependencies) to use TypedDict in Python 3.7. In my opinion it's well worth the weight because it provides several other importing typing types like `Protocol` and `TypeAlias`. It's also the gateway to newly-introduced typing constructs as we move forward through new minimum Python versions, so I'd consider it a durable dependency.
