### ISSUE TITLE
feat/Add overlap in chunking parameter

### ISSUE THREAD

**Issue by ron-unstructured** [Unstructured-IO/unstructured#1706]
**Is your feature request related to a problem? Please describe.**
In addition to `num_characters` and `max_characters` in the chunking strategy parameter, it'll be helpful to add `num_overlap_characters`.

**Describe the solution you'd like**
Some overlap between chunks ensures the semantic context doesn't get lost between chunks. 

**Describe alternatives you've considered**
n/a

**Additional context**
Example: LangChain [RecursiveCharacterTextSplitter](https://python.langchain.com/docs/modules/data_connection/document_transformers/text_splitters/recursive_text_splitter) has `chunk_overlap` along with `chunk_size`

**Comment by amanda103** [comment]
Hey @ron-unstructured a few q's on implementation!

1. If `max_characters` is 50 and `overlap` (or whatever var name we choose) is 10, do we add that to the size of the chunk (so we'd have a max of 50 + 10) or account for that in `max_characters` (and only ever return chunks of 50)? My hunch is the latter but let me know!
2. A strange edge case: what if `overlap` is 10, but the next element has a text len of 5, do we include that elements 5 text chars AND 5 chars of the element after that? Just want to know if it's a *hard* number of overlapping characters, or if we can do something like up to `overlap` input if we come across an element with len(chars) < `overlap` input.

Thank you in advance! :)

**Comment by ron-unstructured** [comment]
Hi @amanda103 

1. Your hunch is correct. The overlap is usually accounted for within the `max_characters`.
2. I don't find any information on this edge case. I guess we can go either with the hard number with overlapping elements or use the remaining number of characters.

**Comment by scanny** [comment]
A couple insights into this:

My initial concept was that overlap was something we did on both sides of the chunk. It
turns out however it's a thing that happens completely on the "front" of the chunk and
only second and later chunks at that.

1. Overlap is simply starting the second and subsequent chunks "early", like backing up
   the start index by the overlap value. So in the simple illustrated case, the first
   chunk is s[0:5] as usual, same as when no overlap. The difference starts with the
   next chunk, which instead of starting at 5, starts at (5 - overlap), so 5 - 2 or 3 in
   this case. Its length is still `min(maxlen, remaining_len)`, which is the same for
   all chunks.

2. Chunking continues until the text is consumed (remaining_len is zero). The edge case
   would be that there is only one character remaining, which would produce a terminal
   chunk of length overlap + 1. It's actually not an edge-case per se, just a small
   chunk. One idea that occurred to me is calculating how many chunks it was going to
   take then reducing the maxlen to produce even(ish)-sized chunks. That would avoid the
   "tiny-terminal-chunk" situation. I'm assuming that's too fancy for now but it's an
   idea we might want to consider.

A little bit of the math behind it:

* I use the term _window_ (int) here for the "full" size of a chunk, this would be our
  hard maxlen.
* _step_ (int) is the amount of remaining text consumed by each second and later chunk.
  It is a simple function of window and overlap, `step = window - overlap`
* _tail_ (int >= 0) is the length of text remaining after the first chunk. Each second
  and later chunk includes `step` characters of the tail.
* I use _len_ here for the total length of the text to be chunked.

This is a simple illustration of an example:

```txt
                   1 1 1 1 1 1 1 1 1 1 2 2
 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
 a b c d e f g h i j k l m n o p q r s t .
|         | |         | |         | |         |
+---------+ +---------+ +---------+ +---------+
      |         | |         | |         |
      +---------+ +---------+ +---------+

len     = 21
window  =  5
tail    = 16
overlap =  2
step    =  3
```

* We can see that it takes 7 chunks to consume the text. The _chunk-count_ can be
  computed like this:

  `chunk_count = 1 + (tail + step - 1) // step`

**Comment by amanda103** [comment]
@ron-unstructured can you checkout the change here and just confirm this is the functionality we're looking for? Probably most helpful to read the changelog for how overlap improves chunking :) 

see https://github.com/Unstructured-IO/unstructured/pull/1771

**Comment by ron-unstructured** [comment]
Hi @amanda103 The overlap functionality LGTM. It improves the chunking functionality that we're looking for. 👍

**Comment by adanielyan** [comment]
Has this been implemented? Can I use it in TS SDK?

**Comment by adanielyan** [comment]
Hi Ron, thanks for replying. I know about these 3 params, but none of them seems to enable overlapping. Isn't it correct? This feature request is for adding an overlapping param and it seems it was implemented. But I am not sure how to use it in TS SDK. Is it available there?

**Comment by ron-unstructured** [comment]
Hi @adanielyan you can add the other API Parameters in the TS SDK as shown in the attached screenshot

![sdk](https://github.com/Unstructured-IO/unstructured/assets/138828701/9c027227-6402-47a0-a8ed-70bae628067f)

**Comment by adanielyan** [comment]
OK, it seems the PR with the `overlap` feature hasn't been released/merged into main yet.

**Comment by ron-unstructured** [comment]
Hi @adanielyan thanks for reporting this issue. I'll report it to our engineers.

**Comment by scanny** [comment]
@adanielyan The overlap options have been added and are currently on `main` (although not in the latest release yet as of today).

If you want you can try it out by installing the latest from the `main` branch.

There are a couple concepts to have as background:

There are two kinds of chunks, "normal" chunks and "text-split" chunks. A normal chunk is composed of one or more whole document elements that together fit in the specified chunking window (`max_characters`). However, a single element can be longer than the chunking window and such an element can't fit in a single chunk. These "oversized" elements are divided into two or more chunks using text-splitting.

Overlap is most appropriate to "split" chunks because the coherent semantic unit represented by the document element is disrupted by text-splitting. Overlap can mitigate this disruption by increasing the chance that a whole concept is captured in each split chunk. Call this type of overlap "intra-chunk" overlap.

However, normal chunks generally capture concepts with a clean boundary. So applying overlap between these chunks introduces noise into a chunk with an otherwise clean semantic boundary. You'll need to judge whether this "inter-chunk" overlap is appropriate for your use-case.

There are two arguments to control these separately: `overlap: int = 0` and `overlap_all: bool = False`. By default, no overlap is applied `(0, False)`. If a positive integer is specified for `overlap`, that many characters of _intra-chunk_ overlap are applied. If `overlap_all` is `True`, the same length of _inter-chunk_ overlap is applied.

Let me know if you need more to go on and let us know how you go :)

**Comment by adanielyan** [comment]
@scanny Thank you so much for addressing this issue and providing a detailed explanation of the new overlap feature. I will test it in the next few days and will get back to you!

**Comment by scanny** [comment]
This was merged awhile back. Closing as completed.
