### ISSUE TITLE
bug/docx read fails if no title elements

### ISSUE THREAD

**Issue by tkumpumak** [Unstructured-IO/unstructured#1798]
Recent update has broken docx read if the docx file does not have any title elements.

How to reproduce:
Create docx with no title elements, just add plain text and nothing else.
This in effect causes the newly added title based extraction to fail.

**Comment by cragwolfe** [comment]
CC @scanny

**Comment by scanny** [comment]
@tkumpumak please provide a stack trace so we can know when we've reproduced the error you're seeing.

**Comment by scanny** [comment]
Okay, I found it.

**Comment by scanny** [comment]
**Diagnosis.** This occurs on any `Text` subclass element with the empty string for its text. This occurs routinely in .docx as `PageBreak("")`.

Root cause is missing parens on `text.strip == ""` here: https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/lang.py#L238 which causes that portion of the expression to always evaluate `False` such that empty string text is not detected as intended. (`text.strip` is the function, `text.strip()` is the `str` result of calling that function on `text`.)

Fix should include adding or modifying a test to exercise this case, say by including `PageBreak("")` as one of its elements.

**Comment by tkumpumak** [comment]
I tested that fix and it removes the warning print. However if I compare extracting docx file with no title elements on for example _unstructured 0.8.6_ I get elements out from a call to _partition_docx()_. Then when updating to the current release + this fix. I still do not get any elements from _partition_docx()_ call.

Is the expected behaviour with _partition_docx()_ default parameters that if docx has no titles, then no elements will be returned?

**Comment by tkumpumak** [comment]
Ok so resolved where these files come from. These non-working files come from Microsoft Teams chat export.
Here's one anonymized file that is unextractable in 0.10.24. Tested with 0.8.6 and with that version file can be extracted.

[test.docx](https://github.com/Unstructured-IO/unstructured/files/13052653/test.docx)

**Comment by Coniferish** [comment]
@scanny, are you familiar with any differences with Teams exported files?

**Comment by scanny** [comment]
Hmmmm, very interesting! Taking a look now. This is essentially an extremely stripped-down word file with no document properties, styles, or anything. So we might need to make some adjustments to accommodate these.

But this gives me a clear focus on where to check. I'll report back shortly ... I expect we'll open a new issue once I've put my finger on what's going wrong.

**Comment by scanny** [comment]
Okay, very interesting. It turns out that these stripped-down word files have no sections. So because we iterate over the sections (because that's where headers, footers, and certain page breaks live), we're not finding these paragraphs that are outside any section.

I'm going to have to think about how we handle this special case, but this is a good find. I'll create a new issue for this.

**Comment by scanny** [comment]
@tkumpumak @Coniferish The new issue for this is #1816
