### ISSUE TITLE
bug/docx skip counting page number for blank page

### ISSUE THREAD

**Issue by Klaijan** [Unstructured-IO/unstructured#2012]
**Describe the bug**
Page number was wrongly enumerated when there existed a blank page. For instance, page 1 and page 3 have contents, where page 2 is a blank page. The page number extracted from `elements_to_json` reads content from page 3 as page 2.

**To Reproduce**
```elements_to_json(partition(filename="example-docs/handbook-872p.docx"),"handbook-872p.docx.json")```

**Expected behavior**
A correct page number corresponded to the actual document's page number.

**Screenshots**
![image](https://github.com/Unstructured-IO/unstructured/assets/2177850/c84474ff-ab77-49c2-bf17-e378d5bf7344)
<img width="1104" alt="image" src="https://github.com/Unstructured-IO/unstructured/assets/2177850/0d16ccb6-2251-4dc0-9499-a55e79c22e5c">

**Environment Info**
```
OS version:  macOS-13.4-arm64-arm-64bit
Python version:  3.8.15
unstructured version:  0.8.1
unstructured-inference version:  0.7.10
pytesseract version:  0.3.10
Torch version:  2.1.0
Detectron2 is not installed

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
PaddleOCR is not installed
Libmagic version:  ==> libmagic: stable 5.45 (bottled)
LibreOffice version:  ==> libreoffice: 7.6.2
```

**Additional context**
1.
The page numbers do not seem to update after the Table of Content. For example, below is the text from page 8 in the document, but is shown as page 2 in metadata. (It seem to be running as according to the footer's page number, but more investigation is needed.)
![image](https://github.com/Unstructured-IO/unstructured/assets/2177850/0e7c9aec-6dfb-4011-b5d0-41cace74ac70)

2.
Not quite related to this issue, but do we consider trimming the text extracted?
![image](https://github.com/Unstructured-IO/unstructured/assets/2177850/8ab14b85-ee10-47d1-80e9-fb081fda8cf3)
<img width="612" alt="image" src="https://github.com/Unstructured-IO/unstructured/assets/2177850/31da89f7-b9d1-431d-8f6d-5e49435c8384">

**Comment by scanny** [comment]
This behavior is addressed in a PR of mine merged last week.

Unfortunately the new behavior in this case is to not report any page numbers at all, the reason being the `handbook-872p.docx` file contains no rendered page breaks. This could be because it was a conversion from the original.

In any case, I'm pretty sure I can get Word to pop those in there for us if you think that would be better. I expect it would make it a better example if end-users were likely to use it like that, but I've got the enough other test-files in there for unit-testing purposes.
