### ISSUE TITLE
With `chipper` and `partition_via_api`, `hi_res_model_name='chipper'` returns an error.

### ISSUE THREAD

**Issue by piegu** [Unstructured-IO/unstructured#2272]
**Describe the bug**
With `chipper` and `partition_via_api`:
- `hi_res_model_name='chipper'` returns an error.
- but `model_name='chipper'` works.

With `yolox` and `partition_via_api`: 
- both `hi_res_model_name='yolox'` and `model_name='yolox'` do not return an error.

**To Reproduce**
```
from unstructured.partition.api import partition_via_api

# partition_via_api parameyters: https://unstructured-io.github.io/unstructured/apis/api_parameters.html
elements = partition_via_api(
  filename=filename, api_key="xxxx", 
  strategy="hi_res", 
  pdf_infer_table_structure=True,
  hi_res_model_name='chipper'
)
```
Error message:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-192-a379f31cfc40>](https://localhost:8080/#) in <cell line: 4>()
      2 
      3 # partition_via_api parameyters: https://unstructured-io.github.io/unstructured/apis/api_parameters.html
----> 4 elements = partition_via_api(
      5   filename=filename, api_key="xxxx",
      6   strategy="hi_res",

[/usr/local/lib/python3.10/dist-packages/unstructured/partition/api.py](https://localhost:8080/#) in partition_via_api(filename, content_type, file, file_filename, api_url, api_key, metadata_filename, **request_kwargs)
     99         return elements_from_json(text=response.text)
    100     else:
--> 101         raise ValueError(
    102             f"Receive unexpected status code {response.status_code} from the API.",
    103         )

ValueError: Receive unexpected status code 400 from the API.
```

**Expected behavior**
Well, the question is: which parameter do we must use? `hi_res_model_name` or `model_name`?

**Environment Info**
- unstructured==0.11.2 
- unstructured-inference==0.7.15

**Comment by awalker4** [comment]
We just fixed a bug with Chipper in the api, so this 400 response should be fixed! As for the param name:

* The library uses `model_name`
* The api uses `hi_res_model_name` and remaps the param when it calls the library
* So, in this case, `model_name` is not a known param to the api and is ignored. This works because it just uses the default model

See [this issue](https://github.com/Unstructured-IO/unstructured-api/issues/315) for cleaning up the params. We're going to add `hi_res_model_name` to the library and deprecate `model_name` so it's all consistent.
