### ISSUE TITLE
bug/Unstructured 0.11.4 from PyPl repository appears to be missing unstructured.partition.pdf

### ISSUE THREAD

**Issue by leohpark** [Unstructured-IO/unstructured#2286]
**Describe the bug**
The version of unstructured available from PyPl, as the Dec 14 release is missing a file necessary to process PDF files.

**To Reproduce**
from a notebook:
`pip install unstructured`
`from unstructured.partition.pdf import partition_pdf`

**Expected behavior**
unstructured.partition.pdf is part of the library available from PyPl

**Screenshots**
<img width="788" alt="Screenshot 2023-12-16 at 6 01 44 PM" src="https://github.com/Unstructured-IO/unstructured/assets/135409779/9cb5b1ab-db61-4e06-b865-1ce2a7edbe91">

**Environment Info**
Please run `python scripts/collect_env.py` and paste the output here. 
This can be reproduced from a Google Colab notebook and fresh install of unstructured

**Additional context**
Big fan of Unstructured!

**Comment by cragwolfe** [comment]
Thank you for reporting, @leohpark . This is now fixed in 0.11.5. Note that to also install the pdf dependencies that pdf processing requires, you may instead want to:

    pip install "unstructured[pdf]"

More details can be found [here](https://unstructured-io.github.io/unstructured/installation/full_installation.html#full-installation).
Closing since this appears closed with local testing.
