### ISSUE TITLE
bug/partition_html only partially extracts text of element with nested inline tag

### ISSUE THREAD

**Issue by dgunning** [Unstructured-IO/unstructured#2362]
**Describe the bug**
When a html contains a div with a nested  tag e.g. a **b**  or **span**, the element created from the div contains only the text up to the inline element. 

This is likely a behaviour of lxml related to these issues

- [lxml doesn't get all text if text has br](https://stackoverflow.com/questions/29555452/lxml-doesnt-get-all-text-in-element-if-text-has-br)
- [get all text inside a tag in lxml](https://stackoverflow.com/questions/4624062/get-all-text-inside-a-tag-in-lxml)

**To Reproduce**

```python
html = """
<html>
<body>
    <div>
    the Company issues shares at $<div style="display:inline;"><span>5.22</span></div> per share. 
    There is more text
    </div>
</body>
</html>
"""

elements = partition_html(text=html)
print(''.join(e.text for e in elements))
```

This results in

"the Company issues shares at $5.22"

**Expected behavior**
The following should be printed

"the Company issues shares at $5.22 per share. There is more text"

**Screenshots**

**Environment Info**
Please run `python scripts/collect_env.py` and paste the output here. 
This will help us understand more about the environment in which the bug occurred.

**Additional context**

**Comment by kingle-zhuang** [comment]
![1704791657913](https://github.com/Unstructured-IO/unstructured/assets/142277746/0c382804-79b7-446d-bcf3-bcc9ede8d79c)


same issue with it

**Comment by kingle-zhuang** [comment]
missing in the left navigation bar

**Comment by LaverdeS** [comment]
Apparently the problem extends to other examples not using `<div>`:

```
>>> str(partition_html(text='<p>abc <a href="somewhere">def</a><br><strong></strong><strong>ghi</strong></p>')[0])
'abc'
>>> str(partition_html(text='<p>abc <a href="somewhere">def</a><br>ghi</p>')[0])
'abc'
>>> str(partition_html(text='<p>abc <br>ghi</p>')[0])
'abc'
>>> str(partition_html(text='<p>abc ghi</p>')[0])
'abc ghi'
>>> str(partition_html(text='<p>abc <a href="somewhere">def</a> ghi</p>')[0])
'abc def ghi'
>>> str(partition_html(text='<p>abc <br/>ghi</p>')[0])
'abc'
```

ref: [community slack thread](https://unstructuredw-kbe4326.slack.com/archives/C044N0YV08G/p1705412822135569?thread_ts=1705393257.675599&cid=C044N0YV08G)

**Comment by stdweird** [comment]
more examples, with quoting in the mix
```
>>> print([str(x) for x in partition_html(text="<div><ul><li>a</li></ul> b <a href='something'>c</a></div>")])
['a']
>>> print([str(x) for x in partition_html(text="<div><ul><li>a</li></ul> b '<a href='something'>c</a>'</div>")])
['a', "c'"]
```

**Comment by FAbrahamDev** [comment]
Hey everyone, 

I've looked at the HTML parser and think I found a solution. But I don't fully understand the intention of the original code. 

### Source of the problem

The problem is with etree and the html parser as mentioned here https://stackoverflow.com/questions/4770191/lxml-etree-element-text-doesnt-return-the-entire-text-from-an-element
The .text property doesn't return the full text of an element and in general is kinda weird. 
Used here: https://github.com/Unstructured-IO/unstructured/blob/7378a378f65f8f59304e5a20164bc44fbe3c03dd/unstructured/documents/html.py#L187

Now to what I don't understand in the original code:
Was it intended that tag_elem.text should return `the Company issues shares at $5.22 per share. \n There is more text`?   
And the emphasized_texts contains a list of containing string? (Which can be achieved with tag_elem.xpath("string()"))

Or should the .text only include `the Company issues shares at $ per share. \n There is more text` without the 5.22 span.
Anyway, if it doesn't include the 5.22 the ordering of the elements becomes difficult. (this could be achieved with tag_elem.xpath("text()") and join the strings)

### Solution

If we just drop in replace the tag_elem.text with tag_elem.xpath("string()") this has the problem that the output becomes:
```
[ `the Company issues shares at $5.22 per share. \n There is more text`, `5.22`]
```
as the span is a next element in article.iter().

To solve this, the function _get_emphasized_texts_from_tag(tag_elem) could return the found emphasized texts and add them to the descendanttag_elems. 
https://github.com/Unstructured-IO/unstructured/blob/7378a378f65f8f59304e5a20164bc44fbe3c03dd/unstructured/documents/html.py#L183

To something like this: 
```
emphasized_texts, found_tag_elements = _get_emphasized_texts_from_tag(tag_elem)
descendanttag_elems = descendanttag_elems + tuple(found_tag_elements)
```

with this function:

https://github.com/Unstructured-IO/unstructured/blob/7378a378f65f8f59304e5a20164bc44fbe3c03dd/unstructured/documents/html.py#L372
```
def _get_emphasized_texts_from_tag(tag_elem: etree._Element) -> List[Dict[str, str]]:
    """Emphasized text within and below `tag_element`.

    Emphasis is indicated by `<strong>`, `<em>`, `<span>`, `<b>`, `<i>` tags.
    """
    emphasized_texts: List[Dict[str, str]] = []
    tags_to_track = ["strong", "em", "span", "b", "i"]

    if tag_elem.tag in tags_to_track:
        text = _construct_text(tag_elem, False)
        if text:
            emphasized_texts.append({"text": text, "tag": tag_elem.tag})

    found_tag_elements = []
    for descendant_tag_elem in tag_elem.iterdescendants(*tags_to_track):
        text = _construct_text(descendant_tag_elem, False)
        if text:
            emphasized_texts.append({"text": text, "tag": descendant_tag_elem.tag})
            found_tag_elements.append(descendant_tag_elem)

    return emphasized_texts, found_tag_elements
```

I've modified the remaining occurrences of _get_emphasized_texts_from_tag to ignore the second return value, and it seems to work as intended. 

Could someone from unstructured test that?

**Comment by dgunning** [comment]
It should return `the Company issues shares at $5.22 per share. \n There is more text`

Looks like you are on the right track. However, would it handle divs styled as inline?

`<div>This is a parent with<div style='display:inline'>INLINE TEXT</div></div>`

**Comment by stdweird** [comment]
@dgunning what do you expect as output there?
@FAbrahamDev i think that one other issue is that using `.text` in etree elements, should always keep in mind to also deal with the `.tail` part. see eg https://stackoverflow.com/questions/4770191/lxml-etree-element-text-doesnt-return-the-entire-text-from-an-element

**Comment by dgunning** [comment]
@stdweird ignore the last comment .. it works for inline divs

```
def partition(text):
    elements = partition_html(text=text)
    return ''.join(e.text for e in elements)

partition('<div>The company issued a dividend of <div style="display:inline">$5.00</div> per share</div>')

```

The company issued a dividend of $5.00 per share

**Comment by FAbrahamDev** [comment]
> @dgunning what do you expect as output there? @FAbrahamDev i think that one other issue is that using `.text` in etree elements, should always keep in mind to also deal with the `.tail` part. see eg https://stackoverflow.com/questions/4770191/lxml-etree-element-text-doesnt-return-the-entire-text-from-an-element

Given the outputs of the different approaches commented by `demented hedgehog`, I don't understand the difference between root.xpath("string()") and the tail approach. 

@dgunning Thank you for checking it. 
I did not find any time over the weekend. 
But it seems to do what was intended?

**Comment by stdweird** [comment]
@FAbrahamDev i don't think there is any difference ;)
it looks like to get text with etree one should use `.xpath("string()")` or some weird combinatio of `.text` and `.tail`

i would however prefer to add a wrapper function `_text_from_etree_element` and use that where needed; instead of repacing `.text` with `.xpath(...)`. one never knows what other cases we will need to handle.

and unittests ;)

**Comment by FAbrahamDev** [comment]
I've tested @dgunnings example: 
```
<div>This is a parent with<div style='display:inline'>INLINE TEXT</div></div>
```
But get a different result: `This is a parent withINLINE TEXTINLINE TEXT`
Because the containing div is not found in _get_emphasized_texts_from_tag, because it's not one of `<strong>`, `<em>`, `<span>`, `<b>`, `<i>`.

I'm not sure what's the correct approach in this example.

Maybe depending on the return value of _get_emphasized_texts_from_tag use .text otherwise use .xpath or your wrapper. 

One could also check if .text and the .xpath approach yield the same solution, which would mean that there is an element inside which needs to be found and excluded for the next iteration?

I think for the purpose of this repo, extracting more in edge cases is better than missing text.

**Comment by FAbrahamDev** [comment]
When we are at it:
```
<div>
    <span>MISSING TEXT.<p>FOUND TEXT <p>1.<p>2.<p>3.<p>4.<p>5.</p></p></p></p></p></p></span>
</div>
```
I found another example where the `MISSING TEXT` is not included in the output if there are too many nested tags. 
When I remove the <p>5.</p> tag, the missing text is included again. 

I do believe that this is intended given the comments in the code, but I think it should probably be reconsidered given that the amount of tags doesn't mean anything for the content length.
I'd prefer if there is a bigger content piece that the chunker should handle the splitting and not a depth check in the HTML.

**Comment by stdweird** [comment]
@FAbrahamDev :+1: on making the depth configurable.

**Comment by stdweird** [comment]
@FAbrahamDev  do you happen to have a patch or PR for this? i would like to give it a try

**Comment by dgunning** [comment]
Yes I think it should have all the letters in some partition

**Comment by stdweird** [comment]
@FAbrahamDev this is a piece of html that should also retrun somethign useful: `"<html><body><div>aa<ul><li>bb</li></ul><b>cc</b></div></body></html>"`
with `.xpath(string)` on the `div`, you get all the text back, incl the list
i tried with only joining the texts of the  foudn_tags element, but that will return `aacc` (but at least not the list), but you expect here something like `['aa', 'bb', 'cc']` i assume

@dgunning wrt tail, i tried replacing all tail with a text tag, it gives partial success; but still finetuneing more.

**Comment by stdweird** [comment]
@dgunning i made a PR https://github.com/Unstructured-IO/unstructured/pull/2483 with some code i am currently using
i have not added any unittests to deal with the examples discussed here. i am unfamiliar with the way the unittests are set up in this repo tbh

**Comment by dgunning** [comment]
@stdweird I just solved a similar bug in my own library where I was appending while iterating a tag's content
This loop copies from one tag to a new tag. But during the iteration the content is moved from the original tag changing the iterator
```python
            for content in ix_tag.contents:
                if content != '\n':
                    new_tag.append(content)
``` 
This is the fix
```python
            # [:] to avoid modifying the list while iterating
            for content in ix_tag.contents[:]:
                if content != '\n':
                    new_tag.append(content)
 ```                   
 
 I'm not 100% sure but I think the same thing is happening inside 
 https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/documents/html.py#L159
 and https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/documents/html.py#L195

**Comment by dgunning** [comment]
I added this to my fork of unstructured and copying your change in and it passes. What do you need to have the test one the PR and the PR to be approved?
```python
def test_partition_html_with_nested_inline_tag():
    html_text = """
     <html>
     <body>
         <div>
         the Company issues shares at $<div style="display:inline;"><span>5.22</span></div> per share. 
         Here is more text
         </div>
     </body>
     </html>
     """
    partitions = partition_html(text=html_text)
    result = "\n".join([str(p) for p in partitions])
    assert 'Here is more text' in result

```

**Comment by dgunning** [comment]
I wrote the following test

```python
def test_nested_divs_containing_nested_spans():
    html_str = """
    <div>
        Head
        <div><span>Nested</span></div>
        Tail
    </div>
    """
    html_document = HTMLDocument.from_string(html_str)
```

The original behaviour is to create multiple indlvidual html elements with "Head", "Nested". (The original code does not create an element for "Tail")

This fix works but puts everything inside 1 element that renders as

"""
Head
        Nested
        Tail
"""

Not sure what the downstream effects are. Will continue testing

**Comment by christinestraub** [comment]
I think the test should be updated like in this PR #2852.

```
html_text = """
<html>
<body>
    <div>
        the Company issues shares at $<div style="display:inline;"><span>5.22</span></div> per share. There is more text
    </div>
</body>
</html>
"""

elements = partition_html(text=html_text)
print(''.join([str(el).strip() for el in elements]))
assert extracted_text == "the Company issues shares at $5.22 per share. There is more text"
```
