### ISSUE TITLE
docs: Improve the codebase docstrings coverage

### ISSUE THREAD

**Issue by pawel-kmiecik** [Unstructured-IO/unstructured#2421]
It seems there are places in the repo missing Python docstrings, which are in general recommended by [PEP-8](https://peps.python.org/pep-0008/#documentation-strings).
We could use a tool like [interrogate](https://github.com/econchick/interrogate) to track down the docstring-missing parts and then to formalize the checks in the make/CI checks.

Additionally, sticking to a common docstrings style/convention (like [Google style docstrings](https://google.github.io/styleguide/pyguide.html#s3.8-comments-and-docstrings)) would make it easier to auto generate the documentation in future.

**Comment by scanny** [comment]
We've made a lot of progress on this over the year. Closing this as we're unlikely to undertake a specific work-package to address what's left. We'll adopt a boy-scout "leave it better than you found it" ethic to fill in any remaining gaps.

Note we can't write meaningful docstrings for code we don't understand, so better this is undertaken during refactoring or when otherwise assuming ownership/responsibility for an area of the code, rather than in some kind of wholesale effort.

Google-style docstrings are fine when called for, and the best of the standardized formats I've seen, but oftentimes when methods are short and fully type annotated as they should be are mostly boilerplate that would repeat what is fully expressed by the call signature and a punchy docstring. But anyone taking the time to author a useful docstring can make that call for themselves. Focus should be on communicating how to use the function rather than slavish compliance to a standard. Let us each write something that helps the next reader (or future us) to quickly get the gist :)
