### ISSUE TITLE
bug/PDF text extraction failed

### ISSUE THREAD

**Issue by jimmyzzxhlh** [Unstructured-IO/unstructured#2453]
**Describe the bug**

Partitioning the following PDF throws the following error and will get stuck:
https://www.aetnamedicare.com/documents/individual/2024/eoc/Y0001_H5521_127_PQ05_EOC24_C.pdf

```
('Unhandled', 6)
PDF text extraction failed, skip text extraction...
```

I've tried some different PDFs and they work OK. 

**To Reproduce**

Save the PDF file to somewhere, and then:

```
from unstructured.partition.pdf import partition_pdf

elements = partition_pdf(
   <pdf_file_path>,
    strategy="hi_res",
    include_page_breaks=True,
    infer_table_structure=True,
    extract_element_types=["Table"],
    model_name="yolox",
)

```

**Environment Info**
I'm not sure how to run `python scripts/collect_env.py`. I'm using poetry for my project to install unstructured as a dependency. The unstructured library does not seem to have `scripts/collect_env.py` included.

**Comment by christinestraub** [comment]
Hi @jimmyzzxhlh, 

This error indicates that the PDF file has some content that cannot be extracted by the `pdfminer` library. In this case, the "hi_res" strategy partitioning uses OCRed text and does not get stuck.

**Comment by christinestraub** [comment]
Closing as inactive.

**Comment by issahammoud** [comment]
Hi @christinestraub,

I had a similar "warning" message recently, I don't really know when it started to show up.
`bad start page number
PDF text extraction failed, skip text extraction...`

It seems a "warning" message because I got the same number of chunks for my PDFs as before. However, I would like to be sure that everything is working as expected. Do you know why this message appears?

Thanks.
