### ISSUE TITLE
bug/<Only element from partition is "Please enable JS and disable any ad blocker">

### ISSUE THREAD

**Issue by StatsAI** [Unstructured-IO/unstructured#2562]
**Describe the bug**
Only element returned from partition is (unstructured.documents.html.HTMLTitle,
 'Please enable JS and disable any ad blocker')

**To Reproduce**
```
!pip install "unstructured[all-docs]"

url = 'https://www.nytimes.com/2024/02/19/world/europe/navalny-letters-russia.html'

from unstructured.partition.auto import partition
elements = partition(url=url, strategy='hi_res', html_assemble_articles=True)

display(*[(type(element), element.text) for element in elements])
```

**Expected behavior**
Partition results (Title, Narrative Text, etc) should be returned

**Environment Info**
Google Colab

**Comment by scanny** [comment]
Fixed by #3218.

Note that the text extracted by the partitioner for this page is modest (about 25 elements) because most of the content is behind a paywall and generated by JavaScript.

But the "preview" content that is actually present in the HTML is correctly partitioned and the `<noscript>` tag that was previously rendered (saying "Please enable JS ...") is no longer present.
