### ISSUE TITLE
bug/<element.metadata.links returns none>

### ISSUE THREAD

**Issue by StatsAI** [Unstructured-IO/unstructured#2577]
**Describe the bug**
Following the instructions from here: https://unstructured-io.github.io/unstructured/examples/chroma.html, 
the issue occurs when I try to populate the links list. Instead of extracting the links, nothing happens. 

**To Reproduce**
```
!pip install "unstructured[all-docs]"
!pip install langchain
!pip install chromadb

from unstructured.partition.html import partition_html

cnn_lite_url = "https://lite.cnn.com/"
elements = partition_html(url=cnn_lite_url)
links = []

for element in elements:
    if element.metadata.links is not None:
        relative_link = element.metadata.links[0]["url"][1:]
        if relative_link.startswith("2024"):
            links.append(f"{cnn_lite_url}{relative_link}")

links
```

**Expected behavior**
The links list should be populated.

**Environment Info**
Google Colab

**Comment by Coniferish** [comment]
Hi @StatsAI,
Thanks for raising this issue. I'm still looking into this, but the following code will work:
```
from unstructured.partition.html import partition_html

cnn_lite_url = "https://lite.cnn.com/"
elements = partition_html(url=cnn_lite_url)
links: list[str] = []

for element in elements:
    if element.links:
        relative_link = element.links[0]["url"][1:]
        if relative_link.startswith("2024"):
            links.append(f"{cnn_lite_url}{relative_link}")

links
```

I'm still looking into why the `link` is showing up as an attribute of `element` and not in `element.metadata`, though.

**Comment by Coniferish** [comment]
Hi @StatsAI, 
The links are actually present in the metadata. They are accessible through `element.metadata.link_urls` as documented [here](https://unstructured-io.github.io/unstructured/metadata.html#additional-metadata-fields-by-document-type). The example you initially referenced needs to be updated, though. 

Though the code I sent above works, it should not be relied upon because that only works because of deprecated code. We will be refactoring the html partitioner in the future and addressing that in the process.
