### ISSUE TITLE
Create a new data connector for Notion

### ISSUE THREAD

**Issue by ajjimeno** [Unstructured-IO/unstructured#260]
Create a data connector that:

* fetches data from Notion.
* stores the content locally (at least temporarily for processing), and runs them through [unstructured.partition.auto](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/auto.py).
* inspiration for processing is available [here](https://github.com/hwchase17/langchain/blob/master/langchain/document_loaders/notion.py)

See [Adding Data Connectors](https://github.com/Unstructured-IO/unstructured/blob/main/Ingest.md#adding-data-connectors) for details on how to get started. Make sure to include a link to this issue when submitting a PR.

**Definition of Done**

* The [checklist](https://github.com/Unstructured-IO/unstructured/blob/main/Ingest.md#the-checklist) has been completed.
* The connector is able to process entries from Notion using the API.
* The connector is able to process a single entry.
* The connector is able to process several entries, with an option to process them recursively.
* The connector can accept any credentials, if necessary.
* The connector should be able of processing documents through [unstructured.partition.auto](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/auto.py).

**Comment by HAKSOAT** [comment]
Hi @ajjimeno I'm looking to pick this up. 

Does fetching data from Notion here refer to extracting the content of pages on Notion or extracting actual files that can be found on a Notion page?

**Comment by ajjimeno** [comment]
Hi @HAKSOAT, thank you for the interest. Yes, the idea to being able of recovering a Notion page and, if there are nested ones recover them as well. I think the term processing might be confusing but the idea is to connect to Notion, recover the page, nested pages and possible additional attached content. The content recovered should be processed by [unstructured.partition.auto](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/auto.py).

**Comment by HAKSOAT** [comment]
Thanks for clarifying. I picked up the Google Drive connector enhancement. I hope to come back to do this when that is done.

**Comment by HAKSOAT** [comment]
Just putting an update here that I am now taking a look at this task.

**Comment by ajjimeno** [comment]
Great! Thanks Habeeb!

**Comment by HAKSOAT** [comment]
Thought to update my thoughts after exploring the Notion API here. I didn't proceed with this because it felt a bit complex to work with Notion's API. 

They use the concept of "blocks". Hence, multiple "blocks" per page with the possibility of nested blocks (say in the case of bullet points or toggles). I believe an approach that builds an actual page first (maybe a markdown file as the result) before passing through will be needed to make this work.

I think the following links will be good places to start from when working on this:

https://developers.notion.com/reference/block
https://developers.notion.com/reference/get-block-children
https://developers.notion.com/reference/property-value-object

**Comment by ajjimeno** [comment]
Thanks for the pointers. Interesting the way it works.
