### ISSUE TITLE
Partition DOC, DOCX, PPT, PPTX: No images detected

### ISSUE THREAD

**Issue by liturrig** [Unstructured-IO/unstructured#2968]
Hello, 
I'am using ustructured io through library to analyze doc, docx, ppt, pptx documento.
When I use the following functions:
- partition_doc;
- partition_docx;
- partition_ppt;
- partition_pptx;
to analyze documents containing images, 
the object returned doens't contain related images.
Is it the right behavior?
Thanks you for answers.

**Comment by scanny** [comment]
@liturrig Yes, this is the expected behavior. The `unstructured` library does not extract images for the DOC, DOCX, PPT, or PPTX formats.

Image extraction will be available for these formats soon on the REST APIs, including the freemium API. For PPT and PPTX that's likely to be within two weeks. For DOC and DOCX somewhat longer.
