### ISSUE TITLE
no element of type PageBreak in doc file

### ISSUE THREAD

**Issue by veredmm** [Unstructured-IO/unstructured#3020]
**Describe the bug**
a .doc document of 3 pages doesn't return elements of type "PageBreak"

**To Reproduce**
elements = partition_doc(filename=fname,include_page_breaks=True)

can't attach here the sample  file :
i took the fake-doc-emphasized-text.doc from doc-samples and add 2 pages to add the pagebreaks

**Comment by veredmm** [comment]
although in the documention it appears it supports :
![image](https://github.com/Unstructured-IO/unstructured/assets/169882103/f8f8431d-2675-4c70-83b6-b6bcb9675908)

**Comment by MthwRobinson** [comment]
@veredmm - That's expected because the document was converted to DOCX from DOC. In that case, the XML element indicating the page break is not always inserted. @scanny can confirm. Regardless, we'll update the docs to reflect that page breaks aren't support for DOC.

**Comment by scanny** [comment]
@veredmm in general, page-breaks are not reliably indicated in the DOCX format. If they are present we detect them, but that's the best that can be done I'm afraid. I'm not sure whether rendered page breaks are reflected in the DOC format and if they are whether those survive conversion. I've never seen them in a converted file but I haven't really looked for them.

The reason these are not reliably indicated is that these page breaks are determined by the renderer and are not specified by the document. The renderer decides when to break pages based on printer settings, margins, available fonts, etc. and can change depending on how the document is rendered. Some renderers will write `<w:lastRenderedPageBreak>` elements to the file, Word often does that, and that's what we detect to emit `PageBreak` elements.

The situation is not unlike printing HTML, to a PDF say. The HTML cannot tell you where the PDF renderer is going to break the page. It doesn't know whether you're printing on A4 or Letter or what fonts are available and their fontmetrics. The HTML just specifies the content and lets the renderer take it from there.

Anyway, if you absolutely need page numbers you can try rendering the document to PDF and partitioning that, otherwise perhaps the safest bet is to turn off page-break elements so the output is at least consistent.

**Comment by MthwRobinson** [comment]
Thanks @scanny! Going to close out this issue based on that response.
