### ISSUE TITLE
For doc documents, skiP_infer_table_types=["doc"] does not take effect

### ISSUE THREAD

**Issue by guici123** [Unstructured-IO/unstructured#3368]
Set skiP_infer_table_types to ["doc"], but the doc document will also default to extracting tables and images

**Comment by scanny** [comment]
The DOC and DOCX format partitioners extract tables unconditionally, i.e. a table in the document produces a `Table` element in the output stream.

These formats (and many others) are sensitive to the `infer_table_structure` argument which determines whether the structure of the table is also written as HTML to `.metadata.text_as_html` for those `Table` elements.

DOC and DOCX can parse tables without additional performance overhead because the table is explicitly stated in the document file.

Inference file formats like TIFF, PNG, and PDF (when the document is scanned/rasterized) require use of more CPU-intensive models to "infer" tables from the pixels of the image, work out row, column, and cell boundaries, etc. Giving users a choice on whether to spend performance/latency on this job is the purpose of the `skip_infer_table_types` parameter and is why it does not apply to DOC.

Closing as assumed resolved.
