### ISSUE TITLE
`partition_pdf` should support documents in two column format

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#356]
The goal of this issue is to add support for two column documents to `partition_pdf`. Currently, `partition_pdf` will process the documents but the elements are not always in the correct order. The attached document can be used for testing.
[Dense-Passage-Retrieval-for-Open-Domain-Question-Answering.pdf](https://github.com/Unstructured-IO/unstructured/files/10944472/Dense-Passage-Retrieval-for-Open-Domain-Question-Answering.pdf)

**Comment by hsm207** [comment]
does this issue also implies adding support for docs with more than 2 columns?

**Comment by MthwRobinson** [comment]
@hsm207 - Yes, this will support multicolumn (two or more columns). In the meantime, you can pass in `strategy="fast"` (if the text is extractable) or `stragey="ocr_only"` (if the text is not extractable) for better results on multi-column documents.

**Comment by Kate-Lyndegaard** [comment]
Hi,
Is this improvement available, yet?

**Comment by walsha2** [comment]
> Is this improvement available, yet?

In tracking the commit history in the `unstructured-inference` repo, it looks like a promising first attempt was added in [#112](https://github.com/Unstructured-IO/unstructured-inference/pull/112) and reverted in [#120](https://github.com/Unstructured-IO/unstructured-inference/pull/120) - then no action since then I presume?

Maybe @MthwRobinson or @qued can comment on the status of this. Is a more sophisticated sorting method the right approach or is that too fragile? Seems like sorting is required no matter what, esp if the text is directly extracted from a pdf. 

@MthwRobinson was on the right track and I think a few more cracks at "smart sorting" might yield a solution that is at least do no harm to single column layouts while also addressing some larger set of multi-column PDFs.

Not sure if there is some other means of solving the multi-column problem that is being tossed around internally but has yet to be disseminated? Wanted to ask first before digging any deeper myself.

**Comment by cragwolfe** [comment]
Yes, there was a significant improvement in reflecting "natural reading order" in https://github.com/Unstructured-IO/unstructured/pull/1161 , which was released in `0.10.6`.

However, there are a couple of open issues to further improve on this:
https://github.com/Unstructured-IO/unstructured/issues/1233
and
https://github.com/Unstructured-IO/unstructured/issues/1209
