### ISSUE TITLE
bug/Error message from partition_json is unhelpful

### ISSUE THREAD

**Issue by awalker4** [Unstructured-IO/unstructured#547]
**Describe the bug**
When `partition_json` receives a json file of the wrong schema, we get the error `ValueError: Json schema does not match the Unstructured schema`. As long as this error is relevant, we should clarify how to proceed.

**To Reproduce**
Created a file hello.json:
```
{
  "hello": "world"
}
```

In a python shell:
```
In [3]: from unstructured.partition.auto import partition
   ...: 
   ...: elements = partition(filename="example-docs/hello.json")
   ...: print("\n\n".join([str(el) for el in elements]))
...
...
ValueError: Json schema does not match the Unstructured schema
```

**Expected behavior**
The error message should clarify what schema is needed. Bonus points: we have some documentation that explains why we need the schema.

**Comment by 5inGularity** [comment]
Looks like the API expects 'content-type' for form elements. I got around by passing content-type as below - 
`
loader = UnstructuredAPIFileLoader(
        content_path,
        url="http://unstructured:4000/general/v0/general",
        content_type="text/html",
)
`

**Comment by ZechenM** [comment]
got a new error after using the unstructedapifileloader:

---------------------------------------------------------------------------
gaierror                                  Traceback (most recent call last)
File [~/cs291i/langchain1/lib/python3.11/site-packages/urllib3/connection.py:200](https://file+.vscode-resource.vscode-cdn.net/Users/zechenma/cs291i/~/cs291i/langchain1/lib/python3.11/site-packages/urllib3/connection.py:200), in HTTPConnection._new_conn(self)
    199 try:
--> 200     sock = connection.create_connection(
    201         (self._dns_host, self.port),
    202         self.timeout,
    203         source_address=self.source_address,
    204         socket_options=self.socket_options,
    205     )
    206 except socket.gaierror as e:

File [~/cs291i/langchain1/lib/python3.11/site-packages/urllib3/util/connection.py:60](https://file+.vscode-resource.vscode-cdn.net/Users/zechenma/cs291i/~/cs291i/langchain1/lib/python3.11/site-packages/urllib3/util/connection.py:60), in create_connection(address, timeout, source_address, socket_options)
     58     raise LocationParseError(f"'{host}', label empty or too long") from None
---> 60 for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
     61     af, socktype, proto, canonname, sa = res

File [/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py:961](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py:961), in getaddrinfo(host, port, family, type, proto, flags)
    960 addrlist = []
--> 961 for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    962     af, socktype, proto, canonname, sa = res

gaierror: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:
...
--> 519     raise ConnectionError(e, request=request)
    521 except ClosedPoolError as e:
    522     raise ConnectionError(e, request=request)

ConnectionError: HTTPConnectionPool(host='unstructured', port=4000): Max retries exceeded with url: /general/v0/general (Caused by NameResolutionError(": Failed to resolve 'unstructured' ([Errno 8] nodename nor servname provided, or not known)"))

**Comment by awalker4** [comment]
Hi there, from the trace it looks like it's trying to make a connection to `http://unstructured:4000` which will complain about being an invalid url. When initializing the loader, please make sure it's either pointing to the hosted api (`https://api.unstructured.io`) or a local instance of the api (probably `http://localhost:8000` or whichever port you've chosen).

Please let me know if this helps, otherwise we can file a new issue and dig a bit deeper. Thanks!

**Comment by 5inGularity** [comment]
Yes, I should have clarified that. I was running under docker with `unstructured` being the service name for hosted API instance.

**Comment by ZechenM** [comment]
Thank you so much to both of you! This api https://api.unstructured.io works!

**Comment by awalker4** [comment]
8000 is the default port if you've cloned the [unstructured-api repo](https://github.com/Unstructured-IO/unstructured-api#developer-quick-start) and you run `make run-web-app`. However, if it's running on a different port for whatever reason, you should be able to track it down in the log when the app starts. Let me know if this helps!

```
$ make run-web-app 
PYTHONPATH=/Users/austin/repos/pipeline-general uvicorn prepline_general.api.app:app --reload --log-config logger_config.yaml
2023-05-18 13:30:37,590 uvicorn.error INFO Will watch for changes in these directories: ['/Users/austin/repos/pipeline-general']
2023-05-18 13:30:37,590 uvicorn.error INFO Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2023-05-18 13:30:37,590 uvicorn.error INFO Started reloader process [21980] using WatchFiles
2023-05-18 13:30:39,181 uvicorn.error INFO Started server process [22019]
2023-05-18 13:30:39,181 uvicorn.error INFO Waiting for application startup.
2023-05-18 13:30:39,181 uvicorn.error INFO Application startup complete.
```

**Comment by korablin** [comment]
also hitting this with a regular JSON file

**Comment by awalker4** [comment]
Going to close this as the error message is a bit more helpful now. [This issue](https://github.com/Unstructured-IO/unstructured/issues/1038) tracks allowing other json inputs.
