### ISSUE TITLE
Add `include_path_in_metadata_filename` kwarg to partition functions

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#605]
The goal of this issue is to add an `include_path_in_metadata_filename` kwarg to the partition functions. If it is `True`, the `filename` attribute in the element metadata should include the full path to the filename and `file_directory` will be `None`. If it is `False`, the `filename` attribute will only contain the filename, and `file_directory` will contain the path. This will help users choose the metadata structure that best suits their use case.

**Comment by Coniferish** [comment]
Should the default for this kwarg be `True` or `False`?

**Comment by Coniferish** [comment]
And should this only apply when partitioning via `filename` and not when via `file`?
Also, what is the desired behavior for this when `metadata_filename` is defined?

**Comment by MthwRobinson** [comment]
We can default to `False` since that's the current behavior. Should apply if there's a value for `metadata_filename`, i.e. if `filename` is used or the user passes in `metadata_filename`.

**Comment by Coniferish** [comment]
So when a user passes in a value to `metadata_filename` and `include_path_in_metadata_filename` is `True`, the metadata.filename should be the value passed to `metadata_filename` + the full path, yes?  I'm wondering if there would ever be a scenario when concatenating those would produce a nonexistent file path.

**Comment by MthwRobinson** [comment]
It could be nonexistent, we don't need to check if it exists though. We're letting the user set the filename in the metadata to whatever they'd like.

**Comment by Coniferish** [comment]
Should this be closed @MthwRobinson? If so, do you want me to close issues myself after a PR has been accepted?

**Comment by Coniferish** [comment]
It looks like I'm going to have to refactor the changes I'd done previously for `metadata_filename` if we want `metadata_filename` + `<path>` to be the filename whenever `include_path_in_metadata_filename` is `True`. Because the changes for `metadata_filename` happen within each parser, the `metadata_filename` is passed as the actual `filename` whenever `ElementMetadata` is initialized, so the `__post_init__` logic that captures the `file_directory` in there results in the `file_directory` being `None` (because the `filename` doesn't necessarily exist in the path), so we're losing the path--didn't realize that was something to pay attention to before
