### ISSUE TITLE
Include heading type in Title's metadata

### ISSUE THREAD

**Issue by saeedesmaili** [Unstructured-IO/unstructured#891]
Related to [this feature request](https://github.com/Unstructured-IO/unstructured/issues/889), it would be nice to have more detailed information about each title in the metadata. For example, the `python-docx` library provides this info as `Heading 1`, `Heading 2`, etc.

**Comment by scanny** [comment]
@saeedesmaili I believe we've added `Element.metadata.parent_id` for this case. It _identifies_ the parent element, rather than describe it, and I don't believe we capture the style-name (e.g. "Heading 1"), but does this give you what you need?

@newelh This `metadata.parent_id` behavior is on `main` now, isn't it?

**Comment by SimranJha2408** [comment]
Believe we can close this?
